### ISSUE TITLE
Errore per la mancata dipendenza da cryptopp del deb

### ISSUE THREAD

**Issue by ocampana** [italia/cie-middleware-linux#11]
Sono riuscito a fare la build del middleware, nonostante le informazioni assenti. In fase di linking la buil fatta con eclipse CDT fa

`g++ -L/home/ottavio/Progetti/cie-middleware-linux/cie-pkcs11 -shared -pthread -o libcie-pkcs11.so cie-pkcs11/CSP/AbilitaCIE.o cie-pkcs11/CSP/ExtAuthKey.o cie-pkcs11/CSP/IAS.o cie-pkcs11/CSP/PINManager.o cie-pkcs11/Crypto/AES.o cie-pkcs11/Crypto/ASNParser.o cie-pkcs11/Crypto/Base64.o cie-pkcs11/Crypto/DES3.o cie-pkcs11/Crypto/MAC.o cie-pkcs11/Crypto/MD5.o cie-pkcs11/Crypto/RSA.o cie-pkcs11/Crypto/SHA1.o cie-pkcs11/Crypto/SHA256.o cie-pkcs11/Crypto/SHA512.o cie-pkcs11/PCSC/APDU.o cie-pkcs11/PCSC/CardLocker.o cie-pkcs11/PCSC/PCSC.o cie-pkcs11/PCSC/Token.o cie-pkcs11/PKCS11/CIEP11Template.o cie-pkcs11/PKCS11/CardContext.o cie-pkcs11/PKCS11/CardTemplate.o cie-pkcs11/PKCS11/Mechanism.o cie-pkcs11/PKCS11/P11Object.o cie-pkcs11/PKCS11/PKCS11Functions.o cie-pkcs11/PKCS11/Slot.o cie-pkcs11/PKCS11/initP11.o cie-pkcs11/PKCS11/session.o cie-pkcs11/Util/Array.o cie-pkcs11/Util/CacheLib.o cie-pkcs11/Util/CryptoppUtils.o cie-pkcs11/Util/IniSettings.o cie-pkcs11/Util/ModuleInfo.o cie-pkcs11/Util/SyncroEvent.o cie-pkcs11/Util/SyncroMutex.o cie-pkcs11/Util/TLV.o cie-pkcs11/Util/UUCByteArray.o cie-pkcs11/Util/UUCProperties.o cie-pkcs11/Util/UUCStringTable.o cie-pkcs11/Util/UUCTextFileReader.o cie-pkcs11/Util/UtilException.o cie-pkcs11/Util/funccallinfo.o cie-pkcs11/Util/log.o cie-pkcs11/Util/util.o -lcryptopp -lcrypto -lpcsclite`

quindi linka contro la libcrypto di sistema in modo dinamico e non in modo statico con la presunta cryptopp presente nel repository.

Questo porta ad avere una dipendenza sulla libcryptopp di systema che non viene segnalata correttamente dal deb generato.

Si propone di:

1. rimuovere la libreria Cryptopp nel repository
2. convertire i sorgenti affinché includano gli header file della libreria di sistema
3. modificare il deb affinché esporti la dipendenza da libcryptopp

**Comment by etmatrix** [comment]
La libreria Cryptopp.a esiste per un motivo ben preciso, non tutte le distribuzioni linux distribuiscono una versione aggiornata della libreria che permette di compilare correttamente.
Debian 10 ed Ubuntu 20.10 distribuiscono la versione 5.6 che non è compatibile con la libreria cie-pkcs11, infatti aggiungendo il parametro `-Wl,-z,defs` al linker si pssono vedere che ci sono dei simboli non risolti.
Ora non so quale sia la versione minima, ma ho visto che fedora 33 distribuisce la versione 8.2 della libreria cryptopp e compila senza usare la versione statica (.a).
Visto che si parla di deb presumo che la versione cryptopp sia troppo vecchia, quindi conviene compilarla dal repository  [ufficiale](https://github.com/weidai11/cryptopp) oppure nel mio [fork](https://github.com/etmatrix/cie-middleware-linux) ho compresso la versione 8.2. Compresso perchè su github c'è il limite di 100MB sui file, oltre bisogna usare github lfs.
