### ISSUE TITLE
conflitti tra licenze

### ISSUE THREAD

**Issue by Germano0** [italia/cie-middleware-linux#16]
Vorrei inserire questo software tra i repository Fedora / EPEL (Red Hat Enterprise Linux e CentOS), ma c'è un problema legale: nonostante il progetto sia rilasciato con licenza BSD 3-Clause, il codice sorgente è pieno di file con licenza non compatibile, come ad esempio [PINManager.h](https://github.com/italia/cie-middleware-linux/blob/924d3804ebd67eecdc4b8a1fdd4d56293c83e372/cie-pkcs11/CSP/PINManager.h) che contiene l'intestazione
```
//  cie-pkcs11
//
//  Created by ugo chirico on 06/10/18. http://www.ugochirico.com
//  Copyright © 2018 IPZS. All rights reserved.)
```

**Comment by paride** [comment]
Questo problema impedisce anche l'inclusione del middleware in Debian e Ubuntu. Notare che lo stesso file LICENSE contiene informazioni contraddittorie ("all rights reserved" ed appena dopo tutti i permessi della 3-clause BSD):
```
Copyright (c) 2017, Developers Italia
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
[...]
```
Ho l'impressione che la nota "all rights reserved" sia stata aggiunta in vari file senza valutarne l'effettivo significato. Purtroppo fino a che la nota permane questo software non potrà essere seriamente considerato Software Libero e nemmeno Open Source secondo la definizione dell'OSI (https://opensource.org/osd).

**Comment by Germano0** [comment]
CC @fottavi

**Comment by FabioLolix** [comment]
CC @ugochirico

**Comment by paride** [comment]
CC @aantetomaso

**Comment by ruphy** [comment]
Cari @parie e @Germano0, grazie di aver trovato questa criticità! Direi che questo conflitto è indubbiamente un problema, e sono portato a pensare che sia una svista dovuta a un template applicato in automatico da parte dello sviluppatore più che una scelta deliberata.
Il problema non è quindi meno grave ma almeno la soluzione sembrerebbe essere semplice, mi prendo in carico con @peppelinux di fare un allineamento interno e verificare che non ci siano problemi nell'eliminare quelle righe.

**Comment by Germano0** [comment]
Penso che solamente Ugo Chirico possa cambiare la licenza del suo codice.
Nel frattempo ho chiesto un parere al team legale di Fedora
https://lists.fedoraproject.org/archives/list/legal@lists.fedoraproject.org/thread/F62LSAKODK6D2UROUKUOFNZXPVHL4RLQ/

**Comment by ruphy** [comment]
@Germano0 il diritto d'autore sul codice non è di Ugo (detentore in questo caso dei soli diritti morali) ma di IPZS che lo ha ingaggiato, e che ci ha appena ri-confermato la volontà di adeguare tutti i file del repository alla licenza adeguata. Dunque possiamo procedere a sistemare l'header dei file.

L'header deve dunque essere modificato nella seguente dicitura:
```
// Copyright (c) the respective contributors, as shown by the AUTHORS file.
```
Mentre il file AUTHORS, da creare, può semplicemente essere
```
Copyright (c) 2018-2022 IPZS

Moral rights:
 Ugo Chirico
 (qui tutti gli altri autori...)
    
The version control system provides attribution for specific lines of code.
```

se qualcuno vuole aprire una PR con questa modifica, è una bella issue per principianti e posso occuparmi di fare revisione e merge!

**Comment by ruphy** [comment]
qui ho adattato il testo di licenza alle policy di progetto che risolvono il problema All Rights Reserved: https://github.com/italia/cie-middleware-linux/commit/06d17c90b46c23678107cde536b5bc1c833b2980

ora tocca solo sistemare gli header dei vari file ed eventualmente aggiungere la metadatazione SPDX

**Comment by Germano0** [comment]
novità????

**Comment by peppelinux** [comment]
Ciao @Germano0, ho rimembranze da Ninux ... :-)

perfavore apri PR e pingami, chiederò ai colleghi che si occupano di questo progetto di revisionare e dare seguito

**Comment by Germano0** [comment]
scusa ma come faccio ad aprire una PR, che presumibilmente dovrebbe alterare il copyright del codice di un altro utente? È lo stesso utente che deve modificarlo, non io!

**Comment by ruphy** [comment]
ho erratamente fatto push del commit su master invece che aprire una PR dedicata. Revert
