### ISSUE TITLE
installazione fallita su CentOS 7

### ISSUE THREAD

**Issue by tojfl** [italia/cie-middleware-linux#19]
Di seguito riporto l'output del comando d'installazione "rpm -i cie-middleware_1.3.1.rpm"

error: Failed dependencies:
	libcrypto.so.1.1()(64bit) is needed by cie-middleware-1.3.1-0.x86_64
	libcrypto.so.1.1(OPENSSL_1_1_0)(64bit) is needed by cie-middleware-1.3.1-0.x86_64
	libstdc++.so.6(CXXABI_1.3.8)(64bit) is needed by cie-middleware-1.3.1-0.x86_64
	libstdc++.so.6(CXXABI_1.3.9)(64bit) is needed by cie-middleware-1.3.1-0.x86_64
	libstdc++.so.6(GLIBCXX_3.4.20)(64bit) is needed by cie-middleware-1.3.1-0.x86_64
	libstdc++.so.6(GLIBCXX_3.4.21)(64bit) is needed by cie-middleware-1.3.1-0.x86_64
	libstdc++.so.6(GLIBCXX_3.4.22)(64bit) is needed by cie-middleware-1.3.1-0.x86_64

La release è: centos-release-7-9.2009.1.el7.centos.x86_64. Dall'output del comando "strings" si evince che le versioni più recenti presenti sono: OPENSSL_1.0.2, CXXABI_1.3.7, GLIBCXX_3.4.19.
Si può ovviare in qualche modo? Posso provare a compilare dai sorgenti?

Grazie

**Comment by etmatrix** [comment]
> Posso provare a compilare dai sorgenti?

Hai provato? Nessuno ti nega di provarci :)
Oggi con eclipse cdt 2021-03 ho ricompilato senza problemi su una debian 10.
