### ISSUE TITLE
Rimozione software CIE

### ISSUE THREAD

**Issue by aantetomaso** [italia/cie-middleware-linux#28]
Prevedere un sistema di uninstall automatico del Software CIE che curi anche la rimozione di tutti i settaggi utente.

**Comment by mavoga** [comment]
Non fatelo. I maintainer script non debbono scrivere in $HOME: è contrario alle policy.

Cfr. p.es.: https://www.debian.org/doc/debian-policy/ch-files.html#configuration-files e https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=902612

**Comment by aantetomaso** [comment]
Grazie del suggerimento, chiudo la issue allora
