### ISSUE TITLE
Messaggio "PIN errato" da Firefox (con PIN corretto)

### ISSUE THREAD

**Issue by udanieli** [italia/cie-middleware-linux#29]
Salve a tutti. Ho abbinato la CIE con il programma CIE ID, installato mediante pacchetto deb ufficiale + driver CCID bit4id scaricato dal sito. Ho provato una firma digitale e funziona.

Non funziona la libreria su Firefox (`/usr/local/lib/libcie-pkcs11.so`):  la carico e vedo la carta presente, ma quando va a fare login mi dà un messaggio di PIN errato. Inutile dire che il PIN lo digito correttamente altrimenti non potrei né abbinare/disabbinare la CIE nel programma CIE ID né tantomeno firmare. Ho provato a disabbinare e riabbinare ma niente.

OS: Debian 10.9
Firefox ESR da pacchetto debian (78.11.0esr) 64bit
CIE middleware: 1.4.0
`bit4id-ccid`: 3.1.1-567

Vi ringrazio anticipatamente

**Comment by M0Rf30** [comment]
usa solo le ultime 4 cifre del PIN

**Comment by udanieli** [comment]
Tremendo, con le ultime 4 cifre funziona

**Comment by udanieli** [comment]
Dove posso vedere i dettagli sanguinolenti di 'sta cosa del mezzo PIN?
