### ISSUE TITLE
Arch Linux package is here

### ISSUE THREAD

**Issue by 00sapo** [italia/cie-middleware-linux#32]
Ho creato il pacchetto per arch-linux usando `debtap`. Non ho ricompilato nulla, ho solo riconvertito il pacchetto ufficiale debian con `debtap cie-middleware_1.4.1.deb`.

Se rilasciaste l'ultima versione con `_latest` o `_stable` sarebbe possibile mantenere aggiornati tutti questi pacchetti di installazione automatici invece di dover ogni volta ricompilarli solo per cambiare il numero di versione.

**Comment by FabioLolix** [comment]
[cie-middleware-bin](https://aur.archlinux.org/packages/cie-middleware-bin) esiste su AUR

**Comment by 00sapo** [comment]
Sì ma da un repo apposito, non verificato. Brutta cosa direi per un software di cifratura... ecco l'aur del pacchetto ufficiale https://aur.archlinux.org/packages/cie-middleware-deb/

**Comment by FabioLolix** [comment]
cie-middleware-bin scarica https://github.com/italia/cie-middleware-linux/releases/download/1.4.1/cie-middleware_1.4.1.tar.gz, non creare duplicati senza valido motivo su AUR

**Comment by FabioLolix** [comment]
Comunque manca la dipendenza su java-runtime per lanciare il programma e ed è presente riscv64-linux-gnu-glibc

**Comment by 00sapo** [comment]
Scusami, avevo visto il cie-middleware-git che mi ha confuso le idee. Ad ogni modo le dipendenze sono quelle del pacchetto debian (che non ha java runtime, non so se è installato di default su tutte le distro debian...) e non so perché abbia tirato fuori riscv64, ma suppongo che un motivo ci sia.

Io cancello il pacchetto deb, ma sarebbe carino (credo doveroso) specificare nelle descrizioni che il pacchetto `-git` compila da sorgenti non ufficiali, mentre il `-bin` usa i compilati ufficiali. Lo metto come commento su aur...

**Comment by 00sapo** [comment]
Resta il discorso di rilasciare l'attuale versione stabile con un link gnerico indipendente dal numero di versione...

**Comment by FabioLolix** [comment]
Nel tuo pkgbuild creato con debtap

* manca la licenza in ${pkgdir}/usr/share/licenses/${pkgname}/
* arch 'i686' non viene usato
* groups=('') si può cancellare
* non c'è correlazione fra pkgver= e source=()

**Comment by FabioLolix** [comment]
> ma sarebbe carino (credo doveroso) specificare nelle descrizioni che il pacchetto -git compila da sorgenti non ufficiali

Nella descrizione del -git è specificato '(mio fork)' ed sono usati tag 'unofficial' e 'fork', comunque si può migliorare ancora, avevo già revisionato dei pkgbuild di M0Rf30 ma devo ancora finire

**Comment by 00sapo** [comment]
Sì, però ci sono mille tag. Io cambierei proprio il nome del pacchetto perché così sembra che derivi questo repo. Io per scrupolo ho controllato e mi sono accorto che il repo era un altro, completamente diverso. Al che non mi sono fidato dei due pacchetti, che dal nome sembrano correlati.

**Comment by FabioLolix** [comment]
> Io cambierei proprio il nome del pacchetto

Si, sarebbe da fare
