### ISSUE TITLE
Package 1.4.1 per Debian non va con Firefox 96

### ISSUE THREAD

**Issue by mxmanghi** [italia/cie-middleware-linux#34]
Un recente upgrade di Firefox (v96.0.2) ha rotto la compatibilità binaria con la versione libcie-pkcs11.so distribuita come v1.4.1.

Inoltre c'è un problema con il package Debian che ha nel nome la versione 1.4.1 ma si installa ancora come 1.4.0

**Comment by aantetomaso** [comment]
Risolta nella release 1.4.3.1
