### ISSUE TITLE
Card not recognized by this middleware

### ISSUE THREAD

**Issue by callegar** [italia/cie-middleware-linux#37]
My ID card appears not to be recognized by this middleware.

Matching the ATR with those in https://github.com/italia/cie-middleware-linux/blob/5e4cdceb3449a109efe708f1f83bc12a7400ca2b/cie_sign_sdk/src/CSP/IAS.cpp#L265-L292 there seems to provide a complete match.

My ATR is 3B 8F 80 01 80 31 80 65 B0 85 04 00 11 12 0F FF 82 90 00 8A

Do valid CIE ID cards exist that are not supported by this middleware? The card appears to work with the android CIEID app. Does that app support a superset of the CIEs supported by this middleware?

**Comment by aantetomaso** [comment]
Risolta nella release 1.4.3.1

**Comment by callegar** [comment]
Still not working. Note that I am trying to use the card with the *remotesmartcardreader* in https://frankmorgner.github.io/vsmartcard/remote-reader/README.html as I do not have a stand alone reader. Applied the latest out of tree patch (https://github.com/frankmorgner/vsmartcard/issues/201#issuecomment-1130577266) there too.

Weird enough, now trying to debug with `pkcs11-tool --module /usr/local/lib/libcie-pkcs11.so -I -L` aborts

```
File INI:/usr/local/lib/ciepki.ini
Inizio Sessione - versione: May 13 2022 21:18:01Lib log level: 3
Lib log level: 3
Lib log level: 3
Lib log level: 3
Lib log level: 3
Lib log level: 3
Lib log level: 3
Lib log level: 3
Cryptoki version 2.10
Manufacturer     IPZS
Library          CIE PKCS11 (ver 1.0)
Lib log level: 3
Lib log level: 3
Available slots:
Slot 0 (0x2): Lib log level: 3
Lib log level: 3
Virtual PCD 00 0
  (empty)
Slot 1 (0x1): Lib log level: 3
Lib log level: 3
Virtual PCD 00 0
Lib log level: 3
Lib log level: 3
Lib log level: 3
Lib log level: 3
Lib log level: 3
Lib log level: 3
  (token not recognized)
Lib log level: 3
Lib log level: 3
Lib log level: 3
Lib log level: 3
Using slot 1 with a present token (0x1)
Lib log level: 3
Lib log level: 3
free(): double free detected in tcache 2
Aborted (core dumped)
```
