### ISSUE TITLE
Merge nel repository principale / release

### ISSUE THREAD

**Issue by fgaz** [italia/cie-middleware-linux#4]
Vedo che il repository principale (https://github.com/italia/cie-middleware-linux) ha molti più commit rispetto a questo, e anche 4 release. Sarebbe possibile integrare la compatibilità linux direttamente lì?

Se invece i nuovi commit sul repo principale sono esclusivamente specifici per windows e dunque ha senso mantenere la separazione (dal changelog non mi sembra però), è possibile avere una release per linux?
(sto pacchettizzando `cie-middleware` per NixOS)

**Comment by sfaragnaus** [comment]
Questo repo era pensato per diventare il punto d'incontro tra la versione Linux e quella Windows, tanto è vero che è possibile compilare per entrambe le piattaforme. Gli ultimi commit di Novembre dello scorso anno erano mirati ad avere una gerarchia delle directory che potesse migliorare ulteriormente il merge con il repo per windows in modo da unificare in un solo repo le due versioni. Ho mantenuto l'aggiornamento più o meno fino a poco prima di Novembre rispetto ai nuovi commit del repo Windows, sicuramente andrebbe fatto un aggiornamento agli ultimi commit.

**Comment by ocampana** [comment]
Ci sono novità su questa attività? questo repository è significativamente indietro rispetto al corrispettivo windows.
