### ISSUE TITLE
CIEID non funziona correttamente con OpenJDK v11

### ISSUE THREAD

**Issue by mavoga** [italia/cie-middleware-linux#43]
Con OpenJDK 11 tentando di abbinare una nuova CIE l'applicativo va in crash; con OpenJDK 8 l'abbinamento va a buon fine.

Quando si manifesta il crash nel log si trova questo:

`Internal exceptions (20 events):
Event: 0,224 Thread 0x00007fe0b4594800 Exception <a 'java/lang/NoSuchMethodError'{0x00000000ff2c76d8}: 'java.lang.Object java.lang.invoke.DirectMethodHandle$Holder.invokeSpecial(java.lang.Object, java.lang.Object, int, int, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object)'> (0x00000000ff2c76d8) thrown at [./src/hotspot/share/interpreter/linkResolver.cpp, line 772]
Event: 0,224 Thread 0x00007fe0b4594800 Exception <a 'java/lang/NoSuchMethodError'{0x00000000ff2cb368}: 'java.lang.Object java.lang.invoke.DelegatingMethodHandle$Holder.reinvoke_L(java.lang.Object, int, int, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object)'> (0x00000000ff2cb368) thrown at [./src/hotspot/share/interpreter/linkResolver.cpp, line 772]
Event: 0,228 Thread 0x00007fe0b4594800 Exception <a 'java/lang/NoSuchMethodError'{0x00000000ff16acb0}: 'java.lang.Object java.lang.invoke.Invokers$Holder.linkToTargetMethod(java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object)'> (0x00000000ff16acb0) thrown at [./src/hotspot/share/interpreter/linkResolver.cpp, line 772]
Event: 0,230 Thread 0x00007fe0b4594800 Exception <a 'java/lang/NoSuchMethodError'{0x00000000ff1d7a98}: 'java.lang.Object java.lang.invoke.DirectMethodHandle$Holder.invokeSpecial(java.lang.Object, java.lang.Object, int, int, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object)'> (0x00000000ff1d7a98) thrown at [./src/hotspot/share/interpreter/linkResolver.cpp, line 772]
Event: 0,230 Thread 0x00007fe0b4594800 Exception <a 'java/lang/NoSuchMethodError'{0x00000000ff1db478}: 'java.lang.Object java.lang.invoke.DelegatingMethodHandle$Holder.reinvoke_L(java.lang.Object, int, int, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object)'> (0x00000000ff1db478) thrown at [./src/hotspot/share/interpreter/linkResolver.cpp, line 772]
Event: 0,243 Thread 0x00007fe0b4594800 Exception <a 'java/lang/NoSuchMethodError'{0x00000000fef4eaa8}: 'java.lang.Object java.lang.invoke.DirectMethodHandle$Holder.invokeStatic(java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, int)'> (0x00000000fef4eaa8) thrown at [./src/hotspot/share/interpreter/linkResolver.cpp, line 772]
Event: 0,243 Thread 0x00007fe0b4594800 Exception <a 'java/lang/NoSuchMethodError'{0x00000000fef5b020}: 'java.lang.Object java.lang.invoke.DirectMethodHandle$Holder.invokeStatic(java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, int, int)'> (0x00000000fef5b020) thrown at [./src/hotspot/share/interpreter/linkResolver.cpp, line 772]
Event: 0,244 Thread 0x00007fe0b4594800 Exception <a 'java/lang/NoSuchMethodError'{0x00000000fef67978}: 'java.lang.Object java.lang.invoke.DirectMethodHandle$Holder.invokeStatic(java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, int, int, java.lang.Object)'> (0x00000000fef67978) thrown at [./src/hotspot/share/interpreter/linkResolver.cpp, line 772]
Event: 0,249 Thread 0x00007fe0b4594800 Exception <a 'java/lang/NoSuchMethodError'{0x00000000feffb3a8}: 'java.lang.Object java.lang.invoke.DirectMethodHandle$Holder.invokeStatic(java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, int)'> (0x00000000feffb3a8) thrown at [./src/hotspot/share/interpreter/linkResolver.cpp, line 772]
Event: 0,250 Thread 0x00007fe0b4594800 Exception <a 'java/lang/NoSuchMethodError'{0x00000000fee197d8}: 'java.lang.Object java.lang.invoke.DirectMethodHandle$Holder.invokeStatic(java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, int, int)'> (0x00000000fee197d8) thrown at [./src/hotspot/share/interpreter/linkResolver.cpp, line 772]
Event: 0,250 Thread 0x00007fe0b4594800 Exception <a 'java/lang/NoSuchMethodError'{0x00000000fee38260}: 'java.lang.Object java.lang.invoke.DirectMethodHandle$Holder.invokeStatic(java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, int, int, java.lang.Object)'> (0x00000000fee38260) thrown at [./src/hotspot/share/interpreter/linkResolver.cpp, line 772]
Event: 0,251 Thread 0x00007fe0b4594800 Exception <a 'java/lang/NoSuchMethodError'{0x00000000fee58350}: 'java.lang.Object java.lang.invoke.DirectMethodHandle$Holder.invokeStatic(java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, int, int, java.lang.Object, java.lang.Object)'> (0x00000000fee58350) thrown at [./src/hotspot/share/interpreter/linkResolver.cpp, line 772]
Event: 0,262 Thread 0x00007fe0b4594800 Exception <a 'java/lang/NoSuchMethodError'{0x00000000fed04b90}: 'void java.lang.invoke.DirectMethodHandle$Holder.invokeStaticInit(java.lang.Object)'> (0x00000000fed04b90) thrown at [./src/hotspot/share/interpreter/linkResolver.cpp, line 772]
Event: 10,596 Thread 0x00007fe0340d7000 Exception <a 'java/lang/NoSuchMethodError'{0x00000000fdada190}: 'int java.lang.invoke.DirectMethodHandle$Holder.invokeSpecialIFC(java.lang.Object, java.lang.Object, int)'> (0x00000000fdada190) thrown at [./src/hotspot/share/interpreter/linkResolver.cpp, line 772]
Event: 10,600 Thread 0x00007fe0340d7000 Exception <a 'java/lang/NoSuchMethodError'{0x00000000fd916a08}: 'int java.lang.invoke.DirectMethodHandle$Holder.invokeStaticInit(java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object)'> (0x00000000fd916a08) thrown at [./src/hotspot/share/interpreter/linkResolver.cpp, line 772]
Event: 10,600 Thread 0x00007fe0340d7000 Exception <a 'java/lang/IncompatibleClassChangeError'{0x00000000fd920310}: Found class java.lang.Object, but interface was expected> (0x00000000fd920310) thrown at [./src/hotspot/share/interpreter/linkResolver.cpp, line 839]
Event: 10,601 Thread 0x00007fe0340d7000 Exception <a 'java/lang/NoSuchMethodError'{0x00000000fd923288}: 'void java.lang.invoke.DirectMethodHandle$Holder.invokeStaticInit(java.lang.Object, java.lang.Object)'> (0x00000000fd923288) thrown at [./src/hotspot/share/interpreter/linkResolver.cpp, line 772]
Event: 10,601 Thread 0x00007fe0340d7000 Exception <a 'java/lang/NoSuchMethodError'{0x00000000fd928b70}: 'int java.lang.invoke.DirectMethodHandle$Holder.invokeStaticInit(java.lang.Object, java.lang.Object)'> (0x00000000fd928b70) thrown at [./src/hotspot/share/interpreter/linkResolver.cpp, line 772]
Event: 10,859 Thread 0x00007fe0340da800 Exception <a 'java/lang/NoSuchMethodError'{0x00000000ff3da9f8}: 'java.lang.Object java.lang.invoke.DirectMethodHandle$Holder.invokeStatic(java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, int, int, java.lang.Object)'> (0x00000000ff3da9f8) thrown at [./src/hotspot/share/interpreter/linkResolver.cpp, line 772]
Event: 10,859 Thread 0x00007fe0340d7000 Exception <a 'java/lang/NoSuchMethodError'{0x00000000ff209618}: 'java.lang.Object java.lang.invoke.DirectMethodHandle$Holder.invokeStatic(java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, int, int, java.lang.Object, java.lang.Object)'> (0x00000000ff209618) thrown at [./src/hotspot/share/interpreter/linkResolver.cpp, line 772]`

**Comment by aantetomaso** [comment]
Grazie, duplicato della issue #53
