### ISSUE TITLE
v1.4.3-3 Errori di segmentazione su Ubuntu 22.0.4 con JDK e OpenJDK 11

### ISSUE THREAD

**Issue by resoli** [italia/cie-middleware-linux#53]
Riporto qui la mia esperienza con la release in oggetto.

Segnalo innanzitutto che ci sono incongruenze nella nomenclatura e nella pubblicizzazione della release: 

il testo del link nella [pagina ufficiale](https://www.cartaidentita.interno.gov.it/fornitori-di-servizi/documentazione-middleware-cie/) è:

"Middleware per Linux DEB - scarica la versione 1.4.3.2",

e il link è:

https://github.com/italia/cie-middleware-linux/releases/download/1.4.3.2/CIE-Middleware-1.4.3-3.amd64.deb

Il pacchetto installa questi file:

```
$ dpkg -L cie-middleware
/.
/usr
/usr/local
/usr/local/lib
/usr/local/lib/libcie-pkcs11.so
/usr/share
/usr/share/CIEID
/usr/share/CIEID/cieid.jar
/usr/share/CIEID/logo_circle.png
/usr/share/applications
/usr/share/applications/cieid.desktop
```

Quindi la libreria PKCS11 da caricare in firefox è la

`/usr/local/lib/libcie-pkcs11.so`

Dal file .desktop si può estrarre il comando eseguito per avviare l'applicazione java di gestione (cieid):

```
$ grep Exec /usr/share/applications/cieid.desktop
Exec=java -Xms1G -Xmx1G -Djna.library.path=".:/usr/local/lib" -classpath "/usr/share/CIEID/cieid.jar" it.ipzs.cieid.MainApplication
```

Il comando:

```
java -Xms1G -Xmx1G \
 -Djna.library.path=".:/usr/local/lib" \
 -classpath "/usr/share/CIEID/cieid.jar" \ 
  it.ipzs.cieid.MainApplication
```

Utilizza la libreria installata in `/usr/local/lib` e il jar dell'applicazione lanciando la classe principale `it.ipzs.cieid.MainApplication`

La mia CIE era già "abbinata" (cioè sottoposta alla procedura che mette la prima metà del pin in un file cache cifrato nel profilo dell'utente: `~/.CIEPKI/<serialecarta>.cache` ).

L'applicazione cieid ha mostrato correttamente i dati di abbinamento preesistenti della mia carta

Configurando la libreria

`/usr/local/lib/libcie-pkcs11.so`

In firefox non ho avuto difficoltà nell'accedere al portale dell'anagrafe nazionale:

https://www.anagrafenazionale.interno.it/servizi-al-cittadino/#tab-cie

---
I problemi:

Ho poi provato a "disabbinare" la carta e "riabbinarla" usando la stessa versione di cieid; questa volta ho ottenuto un segmentation fault.

Una volta "abbinata" nuovmente usando il [fork](https://github.com/M0Rf30/cie-middleware-linux) di @M0rf30 ho provato la funzione di firma, sempre con la versione ufficiale, ottenendo segmantation fault sia con la firma CAdES che con la PAdES.

Tutti i segfault sono avvenuti utilizzando la libreria nativa

`libffi8.so`

Ad esempio per il segfault di abbinamento:

```
Stack: [0x00007f0351dc7000,0x00007f0351ec7000],  sp=0x00007f0351ec43c0, free space=1012k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [jna1174822819131949497.tmp+0xeaf8]
C  [libffi.so.8+0x77ec]
C  [libffi.so.8+0x8050]
C  [libffi.so.8+0x7e2e]
```

I dump dei segfault sono disponibili nei file

hs_err_pid<pid del processo java andato in segfault>.log

nella directory da cui si è lanciato il programma.

La distribuzione è `Ubuntu 22.04,` la versione di Java è openjdk (da pacchetto ubuntu) `11.0.17+8-post-Ubuntu-1ubuntu222.04`

**Comment by resoli** [comment]
Aggiornamento:

Ho installato (sempre su Ubuntu 22.04) le versioni 11 e 19 di jre, sia oracle (queste ovviamente disponibli solo da sito Oracle e soggette a login ed accettazione della licenza d'uso proprietaria) che openjdk dai repository ubuntu ufficiali.

Il segfault avviene solo con la versione 11, sia oracle che openjdk, e sempre nell'area di `libjffi.so` .

**Comment by aantetomaso** [comment]
Grazie molte, quindi la issue da diagnosticare è "segfault con JDK e OpenJDK 11 sulle funzionalità di abbinamento e utilizzo carta" giusto?

**Comment by gaber-IT** [comment]
Confermo la presenza del bug anche sulla mia installazione di ArchLinux.
Ho cambiato il JDK di default dalla versione dalla versione OpenJDK 11 alla OpenJDK 19 e tutto ha funzionato senza problemi, sia con CIEID sia con l'autenticazione da browser.

**Comment by IlTecnico** [comment]
Segnalo anche su Ubuntu Mate 22.04 LTS problemi con openjdk versione 11. Ho risolto installando la versione 17.

**Comment by aantetomaso** [comment]
Risolta nella 1.4.3.9
