### ISSUE TITLE
SIGABRT - Chiamata multipla ai distruttori di classe

### ISSUE THREAD

**Issue by AntonioCiccarelli** [italia/cie-middleware-linux#58]
La libreria PKI del CIE Middleware non termina correttamente a causa di un segnale abort in fase di chiusura.
Occorre impedire che si verifichi una situazione del genere, evitando di deallocare due volte la classe CLog.

Da indagare se possano esserci anomalie simili a cascata, poiché potrebbe non essere l'unica afflitta da questo problema.

![image](https://github.com/italia/cie-middleware-linux/assets/118728287/2cbb8905-b421-490f-9466-40303bd939f1)

![image](https://github.com/italia/cie-middleware-linux/assets/118728287/00919012-cfe6-425b-812c-fa43a10be292)

**Comment by mavoga** [comment]
Confermo: questa double free ha anche il fastidioso effetto, tra l'altro, di provocare crash sistematici in altre applicazioni, ad esempio alla chiusura di Libroffice Calc (sempre) e di Okular (quando sono stati visualizzati PDF firmati elettronicamente).

**Comment by aantetomaso** [comment]
Risolta nella 1.4.3.9
