### ISSUE TITLE
La procedura di compilazione presente su README.Linux non funziona

### ISSUE THREAD

**Issue by opensignature** [italia/cie-middleware-linux#6]
La procedura di compilazione descritta su README.Linux non va più. 
Non esiste la directory Build e quindi:
cmake -DCMAKE_MODULE_PATH=`pwd`/../Build/Linux/GCC ../Build/Linux/GCC/
ovviamente non funziona.

Non va nemmeno cmake .. perchè nella root manca il file CMakeLists.txt.

**Comment by svedese** [comment]
nessuna speranza di vedere un aggiornamento?

**Comment by opensignature** [comment]
Quello che non capisco è che se non funziona, perché si è passati ad un file Eclipse o qualunque altro sistema, perché non si cancella da github il README?
La prima cosa che guarda lo sviluppatore C su Linux è se c'è configure, se c'è, ./configure && make && make install e via.
Se non c'è allora legge il README che è lì proprio per quello, per farsi leggere per primo.
Ma se dentro ci sono istruzioni errate che senso ha?

**Comment by M0Rf30** [comment]
ho creato delle risorse di compilazione qui https://github.com/italia/cie-middleware-linux/pull/14. Sono in attesa di risposta, nel frattempo potete dare un'occhiata al mio fork

**Comment by paride** [comment]
Mi accodo alla richiesta. Volevo valutare la possibilità di pacchettizzare il middleware per Debian ma senza istruzioni per compilare (possibilmente usando un sistema standard tipo make o cmake) c'è poco da fare.

**Comment by lancos** [comment]
> Scaricato il repository, installato eclipde e CDT, lanciata la compilazione e fallisce.
> 
> Vi riporto la parte finale dell'output del compilatore, dove si vede che ha problemi a linkare libcryptopp.a
> 
> ```
> g++ -D__STDC_LIB_EXT1__ -I/usr/include/PCSC -O0 -g3 -Wall -c -fmessage-length=0 -fPIC -pthread -o cie-pkcs11/CSP/PINManager.o ../cie-pkcs11/CSP/PINManager.cpp 
> g++ -L/home/ottavio/Progetti/cie-middleware-linux/cie-pkcs11 -shared -pthread -o libcie-pkcs11.so cie-pkcs11/CSP/AbilitaCIE.o cie-pkcs11/CSP/ExtAuthKey.o cie-pkcs11/CSP/IAS.o cie-pkcs11/CSP/PINManager.o cie-pkcs11/Crypto/AES.o cie-pkcs11/Crypto/ASNParser.o cie-pkcs11/Crypto/Base64.o cie-pkcs11/Crypto/DES3.o cie-pkcs11/Crypto/MAC.o cie-pkcs11/Crypto/MD5.o cie-pkcs11/Crypto/RSA.o cie-pkcs11/Crypto/SHA1.o cie-pkcs11/Crypto/SHA256.o cie-pkcs11/Crypto/SHA512.o cie-pkcs11/PCSC/APDU.o cie-pkcs11/PCSC/CardLocker.o cie-pkcs11/PCSC/PCSC.o cie-pkcs11/PCSC/Token.o cie-pkcs11/PKCS11/CIEP11Template.o cie-pkcs11/PKCS11/CardContext.o cie-pkcs11/PKCS11/CardTemplate.o cie-pkcs11/PKCS11/Mechanism.o cie-pkcs11/PKCS11/P11Object.o cie-pkcs11/PKCS11/PKCS11Functions.o cie-pkcs11/PKCS11/Slot.o cie-pkcs11/PKCS11/initP11.o cie-pkcs11/PKCS11/session.o cie-pkcs11/Util/Array.o cie-pkcs11/Util/CacheLib.o cie-pkcs11/Util/CryptoppUtils.o cie-pkcs11/Util/IniSettings.o cie-pkcs11/Util/ModuleInfo.o cie-pkcs11/Util/SyncroEvent.o cie-pkcs11/Util/SyncroMutex.o cie-pkcs11/Util/TLV.o cie-pkcs11/Util/UUCByteArray.o cie-pkcs11/Util/UUCProperties.o cie-pkcs11/Util/UUCStringTable.o cie-pkcs11/Util/UUCTextFileReader.o cie-pkcs11/Util/UtilException.o cie-pkcs11/Util/funccallinfo.o cie-pkcs11/Util/log.o cie-pkcs11/Util/util.o -lcryptopp -lcrypto -lpcsclite 
> /usr/bin/ld:/home/ottavio/Progetti/cie-middleware-linux/cie-pkcs11/libcryptopp.a: file format not recognized; treating as linker script
> /usr/bin/ld:/home/ottavio/Progetti/cie-middleware-linux/cie-pkcs11/libcryptopp.a:1: syntax error
> collect2: error: ld returned 1 exit status
> ```
> 
> Cosa si deve fare per compilare il progetto?

Devi cancellare il file cie-middleware-linux/cie-pkcs11/libcryptopp.a e installare il pacchetto libcrypto++-dev che contiene la libreria per il tuo sistema.

**Comment by M0Rf30** [comment]
Siete ridicoli. Sembra una sfilza di post, dove nessuno sente le ragioni dell'altro. Potevate anche sviluppare per fatti vostri senza mettere su GH. Non siete educati alla collaborazione.

**Comment by lancos** [comment]
Caro Gianluca Boiano, mi sa tanto che dal tuo post quello poco educato sei tu. Se sei stressato (e non se ne capisce nemmeno il motivo) prenditi una camomilla ed evita di scrivere a vanvera e mancare di rispetto.

**Comment by M0Rf30** [comment]
sono calmissimo, generalmente ho un atteggiamento positivo e soprattutto costruttivo (vedesi miei commenti sopra) e la mia PR. Ora, il mio `siete ridicoli` è dovuto ai seguenti motivi:
* rilasciate un software open-source (per di più la Zecca di Stato e di interesse pubblico) e non prendete in carico nessuna richiesta, neanche con un feedback del tipo: "caro utente questo progetto è qui ma è un read-only mirror"
* rilasciate un file binario all'interno di un repo (.a) e con un build system castrato in barba ad ogni best practice, quando fa riferimento ad uno statico facilmente compilabile (cryptopp)
* non c'è alcuna organizzazione interna del codice (ehi ma vi guardate attorno?)
* non c'è un moderatore e non è in alcun modo un repo aperto alla diversità (commit in Italiano? ma dai vi guardate attorno?)

Ora, certo che questo commento rimarrà qui ad ingiallire, la mia è una provocazione per migliorare questo progetto
@lancos dal canto mio: 
* ho aperto un fork, 
* c'è una pipeline attiva che rilascia deb/rpm ad ogni tag, 
* ho integrato, prima del repo ufficiale, un fix per un chip STM (preso dallo sviluppo per Win)
* pacchettizzo codesto software per Arch Linux
* ho cercato di farlo presente e da qui il mio disappunto nel flow di questi post

ed io sarei scostumato? pare che ci credo più di voi in questo progetto onestamente

**Comment by lancos** [comment]
Capisco la tua frustrazione, il progetto sembra un po' abbandonato a se stesso. Ieri sono capitato qui quasi per caso e non riuscendo a fare il build ho risposto con la soluzione che avevo trovato, solo dopo ho notato che si era gia` risposto nella issue #11.
Ho provato a fare il build anche del tuo repo su bionic 18.04 ma richiede una versione di gradle piu` aggiornata

FAILURE: Build failed with an exception.

* Where:
Build file '/home/Projects/cie-middleware-linux/cie-java/build.gradle' line: 7

* What went wrong:
An exception occurred applying plugin request [id: 'com.diffplug.spotless', version: '5.6.1']
> Failed to apply plugin [id 'com.diffplug.spotless']
   > Spotless requires Gradle 5.4 or newer, this was 4.4.1

**Comment by M0Rf30** [comment]
Trovi tutto nel file PKGBUILD del mio fork. Come noterai mi scarico una versione piú aggiornata a build time (essendo quella di sistema vetusta). Essendo gradle una build dependency molto portabile e non richiesta a run-time è l'unica cosa 'custom' che faccio. Per il resto tutte dipendenze trovabili con APT/yum

**Comment by M0Rf30** [comment]
Per ogni perplessità o info sentiti libero di aprire issues. L'unico problema attuale che riscontro è l'impossibilità di usare la libreria in c con Firefox o nss api generica. Per dirla in soldoni, Firefox mi crasha subito e non riesco a fare accesso su Aruba

**Comment by ocampana** [comment]
Con tutto rispetto, non è possibile ripristinare/aggiornare la build di cmake? aveva già anche le regole per fare i deb.

Seconda cosa: ho provato sia qua che sul canale slack, i manutentori del codice sembrano non avere interesse al feedback di terze parti.

**Comment by madduci** [comment]
+1 per la build CMake

**Comment by etmatrix** [comment]
> L'unico problema attuale che riscontro è l'impossibilità di usare la libreria libcie-pkcs11.so con Firefox o NSS Api generica. Per dirla in soldoni, Firefox mi crasha subito e non riesco a fare accesso su Aruba

@M0Rf30 ho lo stesso problema con la loro versione 1.3.1, su firefox 87. Ho provato a ricompilare con eclipse cdt e sia la versione debug che release non si caricano dicendo "non posso aggiungere il modulo", la libreria non viene neanche caricata. Una semplice printf nella funzione di main della so non viene stampata durante il caricamento.
L'unica soluzione che ho trovato è tornare indietro alla versione 1.0 e la libreria su firefox 87 si carica e funziona, sono riuscito ad autenticarmi senza problemi.
Con la versione 1.1 è stato completamente reingenignirazzato il software e da quella versione la libreria non si carica. Non ho provato tutte le build, ma sono quasi sicuro sia con tutte almeno a vedere le varie commit fatte sul codice.
Ho provato sia con una distribuzione debian che ubuntu, proverò con una fedora vediamo se li cambia qualcosa.

**Comment by etmatrix** [comment]
> Devi cancellare il file cie-middleware-linux/cie-pkcs11/libcryptopp.a e installare il pacchetto libcrypto++-dev che contiene la libreria per il tuo sistema.

@lancos bisogna fare attenzione a questo. Il file libcryptopp.a è un puntamento a github lfs perchè il file è troppo grande. Se si cancella e si installa il pacchetto libcrypto++-dev (nome usato in distribuzioni basate su debian) si rischia di usare una versione incompatibile.
Infatti su debian 10 ed ubuntu 20.10 c'è la versione 5.6 a cui mancano delle cose, fedora 33 che usa la versione 8.2 invece funziona senza problemi.
Per essere sicuri di usare la libreria giusta bisogna aggiungere come parametro al linker `-Wl,-z,defs` così in fase di compilazione vengono indicati i simboli non risolti. In caso di simboli non risolti la versione è sbagliata.
Se questo viene ignorato in fase di caricamento su firefox avremo un crash in caso di simboli non risolti.

**Comment by M0Rf30** [comment]
@etmatrix sembra che il problema della libreria che fa crashare firefox, non dipenda da cryptopp.a  e dalla sua presenza. Ho integrato alcuni tuoi fix, ma la cosa è cambiata usando `-lpthread` in fase di linking. Ho fatto commit anche di un meson.build per la libreria e sembra funzionare bene. Tutto sincronizzato con la 1.4.1. Tuttavia ora il bug principale è quello del PIN errato (nonostante sia giusto). Inoltre la parte di signing non funziona proprio, usano una versione forkata di podofo. Insomma lo schifo continua....

**Comment by lgbaldoni** [comment]
> usano una versione forkata di podofo

Ma non potrebbero pubblicare questa fork da qualche parte così che tutti possano usarla?

**Comment by resoli** [comment]
Domanda sciocca, vedo qui il sorgente del middleware, ma non quello dell'applicativo java di gestione (CIEID). Leggendo il manuale si capisce che quest'ultimo va utilizzato almeno una tantum per "abbinare" (sic) la carta, usando l'intero PIN di 8 cifre.

Qualcuno può chiarirmi se ci sia una funzione equivalente qui?

**Comment by resoli** [comment]
> Domanda sciocca, vedo qui il sorgente del middleware, ma non quello dell'applicativo java di gestione (CIEID).

Visto ora la cartella CIEID. Scusate il rumore.

**Comment by rcasta74** [comment]
+ 1 per un sistema di build standard che faciliterebbe la compilazione della libreria per le architetture per cui non viene rilasciata.

Dover installare un IDE solo per compilare una libreria non mi sembra la soluzione corretta. Considerando che c'è chi ha già integrato un sistema di build alternativo in un proprio fork, non capisco perché tale richiesta non venga nemmeno presa in considerazione.

@M0Rf30 grazie per il tuo fork con la build tramite meson: sono così riuscito a compilare la lib sul raspberry.
Per ora ho provato a fare solo un login su un sito pubblico con firefox ed ha funzionato senza problemi.

**Comment by M0Rf30** [comment]
@rcasta74 Il Product Owner del caso (e continua volutamente il mio tono provocatorio, per cercare di smuovere qualcosa), sembrerebbe essere @aantetomaso . Provo a dedurlo dalle poche informazioni su Github, ovvero che lavora per la Zecca e che apre issue come fa un PO sulla kanban, scrivendo le uniche cose da fare che si avverano, dopo secoli, ma si avverano. Confidiamo in te, con la speranza che l'org italia si dia una svegliata in termini di sviluppo collaborativo. O forse la possibilità di poter accedere a tali servizi è volutamente rallentata per favorire i vari provider attivi nella CA (Aruba, Namirial and so on ) e far monetizzare.  Dajeeeee

**Comment by rcasta74** [comment]
Sperando di fare cosa gradita, riporto alcuni link che ho trovato dove viene spiegato come usare eclipse CDT con differenti build tools:

- [CDT/Autotools/User Guide](https://wiki.eclipse.org/CDT/Autotools/User_Guide)
- [CDT/Meson/User Guide](https://wiki.eclipse.org/CDT/Meson/User_Guide)
- [CMake with Eclipse](https://gitlab.kitware.com/cmake/community/-/wikis/doc/editors/Eclipse-UNIX-Tutorial#cmake-with-eclipse)

**Comment by resoli** [comment]
Ho letto questo ormai annoso thread, e per quello che serve scrivo qui al solo scopo di mantenerlo in vita, e di dare un minimo di sostegno e comprensione a @M0Rf30. E' veramente triste vedere un software di rilevanza nazionale lasciato in questo stato; anche se gli utenti Linux sono una nicchia, è una nicchia molto importante e vitale.

**Comment by peppelinux** [comment]
Ciao a tutti, @ruphy mi ha allertato sullo stato di questo repository, ho letto questo thread e mi dispiace molto non essere arrivato prima e sopratutto che da ben due anni la situazione sia andata ristagnandosi sempre di più.

@M0Rf30 e tutti per scambiare due parole e sopratutto in libertà raggiungetemi sul canale slack di developers italia, è un luogo agevole per noi developers.

Se fossimo d'accordo @M0Rf30 io ti proporrei di aprire una PR, così faccio una rapidissima revisione e la unisco subito, dopodiché ci organizziamo su come mantenere questo repository e con dei ruoli chiari e agevoli per tutti

poi, a latere, faremo due chiacchiere per eludere il problema di aggiornamento/collisione di libcrypto++ che mi sembra tanto semplice quanto devastante :-)

Io ci sono, partiamo subito, datemi cenno

**Comment by M0Rf30** [comment]
@peppelinux non so chi tu sia e neanche tu @ruphy. e non verrò in alcun canale slack. apprezzo l'entusiasmo. Probabilmente, qualora le energie me lo permetteranno farò una PR verso questo repo, ma sarà devastante. il mio remote non ha la cronologia correlata con quella di questo repo. quindi passo a voi la palla, mi limiterò ad andare di cherry-pick. Il mio l'ho fatto. qua vedo solo chiacchiere. e le chiacchiere stanno a zero.

**Comment by resoli** [comment]
@peppelinux piacere di vedere che qualcosa si muove. Però credo che prima di ogni altra cosa andrebbe sistemato il README e chiusa questa issue, in modo da permettere a chi è interessato di fare un build. Personalmente per il momento preferisco usare il fork di @M0Rf30, che ha istruzioni chiarissime.

**Comment by opensignature** [comment]
Intanto si muove qualcosa anche lato OpenSC [Add support for Italian CIE 3.0](https://github.com/OpenSC/OpenSC/issues/2486)

**Comment by lgbaldoni** [comment]
> Intanto si muove qualcosa anche lato OpenSC [Add support for Italian CIE 3.0](https://github.com/OpenSC/OpenSC/issues/2486)

Volessero gli dei. Per caso con quella patch si potrebbe fare a meno del baraccone in java, usando solo da browser?

**Comment by opensignature** [comment]
> Volessero gli dei. Per caso con quella patch si potrebbe fare a meno del baraccone in java, usando solo da browser?

Una volta completata sì, purtroppo la patch non è ancora interamente funzionante.

**Comment by lgbaldoni** [comment]
> Una volta completata sì, purtroppo la patch non è ancora interamente funzionante.

Confido che sarà funzionante molto prima di tutto il resto.

**Comment by aantetomaso** [comment]
Ciao a tutti, 

sono in corso sviluppi di  una nuova versione del Software Linux che aggiunge la compatibilità con nuovi processori che presto verranno immessi sul mercato nei prossimi mesi ed introduce un sistema di logging molto più evoluti.
Con l'occasione revisioneremo le istruzioni di compilazione contenute nel README aggiornandole allo stato dell'arte.
La nuova build dovrebbe essere pronta entro il mese di febbraio.
Vi teniamo aggiornati.

**Comment by lgbaldoni** [comment]
@aantetomaso se poteste cortesemente pubblicare anche la fork di PoDoFo fareste contenti molti.

**Comment by resoli** [comment]
> Confido che sarà funzionante molto prima di tutto il resto.

Non sarà uno scherzo @lgbaldoni . Ma vale la pena di completare il supporto OpenSC, anche perchè OpenSC supporta già ottimamente moltissime TS-CNS, una cosa altamente desiderabile se non si vuole impazzire con middleware dedicati per questa o quella carta, e non funzionanti con altre.

**Comment by lgbaldoni** [comment]
@resoli Per capirci, il problema principale è la documentazione o mancanza di beta tester?

**Comment by resoli** [comment]
Non è uno scherzo perché il funzionamento della CIE è complesso, @lgbaldoni. Non inutilmente complesso, beninteso. Da quanto ho potuto leggere nella documentazione tecnica è stato fatto ogni sforzo per mantenere riservatezza e affidabilità nelle comunicazioni tra IFD e ICC, usando Secure Messaging il piú precocemente possibile. In piú la CIEv3 ha anche valenza di documento aderente alle norme ICAO doc 9303, equivalente ad un passaporto.

Peró la documentazione è del 2015[1], e non ho evidenza di aggiornamenti successivi, cosí per capire qualcosa (ad esempio per conoscere gli AID, o il fatto che esistono 5 tipologie di chip) occorre leggere il codice.

[1] https://www.cartaidentita.interno.gov.it/downloads/2021/03/cie_3.0_-_specifiche_chip.pdf

**Comment by resoli** [comment]
Non è uno scherzo perché il funzionamento della CIE è complesso, @lgbaldoni. Non inutilmente complesso, beninteso. Da quanto ho potuto leggere nella documentazione tecnica è stato fatto ogni sforzo per mantenere riservatezza e affidabilità nelle comunicazioni tra IFD e ICC, usando Secure Messaging il piú precocemente possibile. In piú la CIEv3 ha anche valenza di documento aderente alle norme ICAO doc 9303, equivalente ad un passaporto.

Peró la documentazione è del 2015[1], e non ho evidenza di aggiornamenti successivi, cosí per capire qualcosa (ad esempio per conoscere gli AID, o il fatto che esistono 5 tipologie di chip) occorre leggere il codice.

[1] https://www.cartaidentita.interno.gov.it/downloads/2021/03/cie_3.0_-_specifiche_chip.pdf

**Comment by ruphy** [comment]
> Ciao @peppelinux, ottimo vedere rinnovata attenzione per questo progetto. Mi piacerebbe contribuire, magari arrivando ad includere il pacchetto in Debian e Ubuntu. Tuttavia dal mio punto di vista i problemi di licenza sono bloccanti (#16), in quanto rendono di fatto il software non libero e ne rendono impossible l'inclusione nelle distribuzioni.

ciao @paride, su questa almeno abbiamo risolto (vedi #16 e https://github.com/italia/cie-middleware-linux/commit/06d17c90b46c23678107cde536b5bc1c833b2980)

**Comment by opensignature** [comment]
> Volessero gli dei. Per caso con quella patch si potrebbe fare a meno del baraccone in java, usando solo da browser?

La strada su OpenSC è più accidentata del previsto, intanto, proprio per evitare il "baraccone in java", espressione che io condivido totalmente, potete provare https://github.com/opensignature/cie-pkcs11
E' la libreria ufficiale cie-pkcs11 a cui ho aggiunto un sorgente in C++, abilitacie.cpp che abilita la CIE a linea di comando.
Per compilare il tutto è sufficiente "make"

**Comment by resoli** [comment]
> Per compilare il tutto è sufficiente "make"

... dopo aver decompresso libcryptopp.a.xz:

`xz --decompress  libcryptopp.a.xz`

Su alcuni sistemi (es: Manjaro/Arch) può essere necessario aggiungere un

`#include <cstdint>` 

esplicito in uno degli header file (`PCSC/APDU.h` nel mio caso)

**Comment by M0Rf30** [comment]
anzichè mettere sto libcryptopp.a con lfs lo si comprime e carica nel repo sorgente? una cosa molto inelegante da fare. basterebbe usare l'upload degli archivi in releases o packages. Ma poi perchè è necessaria una libreria statica quando si può far affidamento al .so di sistema? proprio non lo capisco. sembra che si voglia nascondere qualcosa. Se questi sono i miglioramenti e il rinnovato interesse....annamo bene

**Comment by resoli** [comment]
> anzichè mettere sto libcryptopp.a con lfs lo si comprime e carica nel repo sorgente? una cosa molto inelegante da fare. 

Credo che il tuo suggerimento sia benvenuto, ma nel posto sbagliato ... andrebbe fatto nel repo di @opensignature.

> Ma poi perchè è necessaria una libreria statica quando si può far affidamento al .so di sistema?

Perché le lib non sono tutte allo stesso livello. Ad esempio la libcypto++ è a v6 su ubuntu lts (20.04). Già provato col tuo build.

**Comment by lgbaldoni** [comment]
@opensignature Ti ringrazio per l'impegno, ma se si devo usare codice chiuso, tanto vale adoperare il pacchetto ufficiale.

Ma questa libcryptopp è patchata o che? Oppure è sempre l'annosa questione della fork segreta di PoDoFo sulla quale non si riesce a ottenere una risposta diretta?

Perché a dirla tutta, e qui chiedo anche agli esperti, se una libreria LGPL viene modificata non andrebbe fornito anche il codice per essere in regola? Altrimenti tutto il pacchetto potrebbe non essere legalmente distribuibile.

**Comment by M0Rf30** [comment]
@lgbaldoni 
esatto. è una violazione della licenza.
https://tldrlegal.com/license/gnu-lesser-general-public-license-v3-(lgpl-3)

**Comment by opensignature** [comment]
> Ma questa libcryptopp è patchata o che? Oppure è sempre l'annosa questione della fork segreta di PoDoFo sulla quale non si riesce a ottenere una risposta diretta?

no, è la cryptopp originale (v.8.7 https://github.com/weidai11/cryptopp). Comunque avete ragione, una libreria compilata e compressa non si può vedere. Cancellata.

**Comment by M0Rf30** [comment]
> > Ma poi perchè è necessaria una libreria statica quando si può far affidamento al .so di sistema?
> 
> Perché le lib non sono tutte allo stesso livello. Ad esempio la libcypto++ è a v6 su ubuntu lts (20.04). Già provato col tuo build.

e per curiosità hai provato a compilare la v6? io la compilo da sempre. se hai provato il mio repo ti trovi il deb compilato "against" la libreria di sistema. quindi, a meno che non ho le traveggole,penso che la tua affermazione sia errata. semmai si gestisce la cosa in maniera diversa, dando le istruzioni per poter compilare la v8  sulle distro target. insomma un po so di cosa stiamo parlando

**Comment by opensignature** [comment]
> e per curiosità hai provato a compilare contro v6? io compilo la libreria cie, da sempre ...

io ho provato con la 5.6.4-8 e non va
Crypto/Base64.cpp: In member function ‘std::__cxx11::string& CBase64::Encode(ByteArray&, std::__cxx11::string&)’:
Crypto/Base64.cpp:27:15: error: ‘byte’ is not a member of ‘CryptoPP’
     CryptoPP::byte* encoded = new CryptoPP::byte[sink.AvailableSize()];
e una serie di altri errori

gli header di cryptopp presenti in questo repo rimandano alla 8.2 (v. https://github.com/italia/cie-middleware-linux/blob/master/cie-pkcs11/Cryptopp/config.h#L104 )
Le distro montano:

- debian sid-> 8.6.0-2
- debian 11 -> 8.4.0-1
- ubuntu 21.10 -> 8.4.0-1
- ubuntu 20.04  -> 5.6.4-9
- debian 10  -> 5.6.4-8
- ubuntu 18.04 -> 5.6.4-8

**Comment by lgbaldoni** [comment]
> Non sarebbe meglio utilizzare una versione per tutti, usando un gestore di dipendenze tipo conan o vcpkg o CMake "External-Project" e linkare staticamente tale libreria?

A far bene sì. A far meglio, CMake potrebbe controllare se la versione disponibile è sufficientemente recente e usare quella oppure compilare l'altra.

**Comment by ocampana** [comment]
> Non sarebbe meglio utilizzare una versione per tutti, usando un gestore di dipendenze tipo conan o vcpkg o CMake "External-Project" e linkare staticamente tale libreria?

no, linkare staticamente non è una buona idea. Se la distro ti dà un aggiornamento di sicurezza della libreria cryptopp non ne potrai beneficiare.

La solzuione corretta è dipendere dalla cryptopp della distribuzione e non compilarla staticamente

**Comment by resoli** [comment]
> > > Ma poi perchè è necessaria una libreria statica quando si può far affidamento al .so di sistema?
> > 
> > 
> > Perché le lib non sono tutte allo stesso livello. Ad esempio la libcypto++ è a v6 su ubuntu lts (20.04). Già provato col tuo build.
> 
> e per curiosità hai provato a compilare contro v6? 

Sí, ho compilato sulla mia 20.04 su cui ho una crypto++.6 ma poi (se non ricordo male, ho fatto build di almeno 5 fork diversi) avevo errori a runtine per mancanza simboli.

> io compilo la libreria cie, da sempre. se hai provato il mio repo ti trovi il [deb compilato](https://github.com/M0Rf30/cie-middleware-linux/releases/download/1.3.2/cie-middleware_1.3.2-0ubuntu1.focal_amd64.deb) "against" la libreria di sistema. quindi, a meno che non ho le traveggole,penso che la tua affermazione sia errata. 

puó essere, tra l'altro posso fare solo prove molto parziali, non disponendo di una cie. Di solito provo con un pkcs11-tool --module libcie-pkcs11.so -I (oppure -L)

> semmai si gestisce la cosa in maniera diversa, dando le istruzioni per poter compilare la v8 o la v6 sulle distro target. insomma un po so di cosa stiamo parlando

Non dubito.

**Comment by M0Rf30** [comment]
> > e per curiosità hai provato a compilare contro v6? io compilo la libreria cie, da sempre ...
> 
> io ho provato con la 5.6.4-8 e non va Crypto/Base64.cpp: In member function ‘std::__cxx11::string& CBase64::Encode(ByteArray&, std::__cxx11::string&)’: Crypto/Base64.cpp:27:15: error: ‘byte’ is not a member of ‘CryptoPP’ CryptoPP::byte* encoded = new CryptoPP::byte[sink.AvailableSize()]; e una serie di altri errori
> 
> gli header di cryptopp presenti in questo repo rimandano alla 8.2 (v. https://github.com/italia/cie-middleware-linux/blob/master/cie-pkcs11/Cryptopp/config.h#L104 ) Le distro montano:
> 
> * debian sid-> 8.6.0-2
> * debian 11 -> 8.4.0-1
> * ubuntu 21.10 -> 8.4.0-1
> * ubuntu 20.04  -> 5.6.4-9
> * debian 10  -> 5.6.4-8
> * ubuntu 18.04 -> 5.6.4-8

puoi provare dal mio fork? ti basta usare le istruzioni o guardare nei PKGBUILD, il problema di `byte` è fixato


> puó essere, tra l'altro posso fare solo prove molto parziali, non disponendo di una cie. Di solito provo con un pkcs11-tool --module libcie-pkcs11.so -I (oppure -L)
puoi provare a caricare la libreria in nssdb (per chrome) con:

`modutil -dbdir sql:~/.pki/nssdb/ -add "CIEID" -libfile /usr/lib/libcie-pkcs11.so`

se è quello che intendi. l'unico problema che ho nel fork attualmente l'errore di PIN sempre errato.
altro trucco per la compilazione è esplicitare l'uso di pthread in fase di linking di pthreads. puoi dare un occhio [qui](https://github.com/M0Rf30/cie-middleware-linux/blob/main/libcie-pkcs11/meson.build)

**Comment by resoli** [comment]
rispondo per la mia parte ...

> puoi provare a caricare la libreria in nssdb (per chromium) con:
> 
> `modutil -dbdir sql:~/.pki/nssdb/ -add "CIEID" -libfile /usr/lib/libcie-pkcs11.so`
> 
> se è quello che intendi. 

piú o meno, pkcs11-tool è parte di OpenSC. Ma proverò anche con modutil, grazie.

> l'unico problema che ho nel fork attualmente l'errore di PIN sempre errato. 

Non è per faccenda del mezzo pin in cache su filesystem?

> altro trucco per la compilazione è esplicitare l'uso in fase di linking di threads. puoi dare un occhio [qui](https://github.com/M0Rf30/cie-middleware-linux/blob/main/libcie-pkcs11/meson.build)

ok, grazie delle dritte.

**Comment by opensignature** [comment]
> puoi provare dal mio fork? ti basta usare le istruzioni o guardare nei PKGBUILD, il problema di `byte` è fixato

provato, build ok ma runtime no: 
pkcs11-tool -O --module ./libcie-pkcs11.so 
sc_dlopen failed: ./libcie-pkcs11.so: undefined symbol: _ZN8CryptoPP20StreamTransformation16ProcessLastBlockEPhPKhm
error: Failed to load pkcs11 module

con cryptopp da 6.1 a salire anche a runtime ok

**Comment by M0Rf30** [comment]
> > puoi provare dal mio fork? ti basta usare le istruzioni o guardare nei PKGBUILD, il problema di `byte` è fixato
> 
> provato, build ok ma runtime no: pkcs11-tool -O --module ./libcie-pkcs11.so sc_dlopen failed: ./libcie-pkcs11.so: undefined symbol: _ZN8CryptoPP20StreamTransformation16ProcessLastBlockEPhPKhm error: Failed to load pkcs11 module
> 
> con cryptopp da 6.1 a salire anche a runtime ok

e dunque bisognerebbe compilare in un pacchetto separato cryptopp alla versione piu recente se ho capito bene. lo posso fare tranquillamente. purtroppo PPA su launchpad non sembrano esserci

**Comment by opensignature** [comment]
> e dunque bisognerebbe compilare in un pacchetto separato cryptopp alla versione piu recente. si a quel punto ha senso usare una soluzione a build time come suggerisce @madduci

le versioni compilate della 8.4 su launchpad già ci sono:
https://launchpad.net/ubuntu/impish/+source/libcrypto++

**Comment by opensignature** [comment]
> > e dunque bisognerebbe compilare in un pacchetto separato cryptopp alla versione piu recente. si a quel punto ha senso usare una soluzione a build time come suggerisce @madduci
 
le versioni compilate della 8.4 su launchpad già ci sono: https://launchpad.net/ubuntu/impish/+source/libcrypto++

e comunque dalla prossima LTS di Ubuntu (la 22.04 Jammy Jellyfish) ci saranno le librerie aggiornate, quindi forse non conviene perderci tutto sto tempo

**Comment by madduci** [comment]
Onde evitare troppe frammentazioni e compatibilità, gestire direttamente la
dipendenza e decidere qualche versione usare sembrerebbe la soluzione più
semplice.

Per assurdo, basterebbe un semplice file conanfile.txt ed un CMakeLists.txt
che importi il file generato da conan:

```txt
[requires]
cryptopp/8.5.0

[generators]
cmake_find_package
```

**Comment by aantetomaso** [comment]
Aggiornato il README con procedura corretta di compilazione
[output-build-Eclipse.txt](https://github.com/italia/cie-middleware-linux/files/8134213/output-build-Eclipse.txt)
[output-build-README.txt](https://github.com/italia/cie-middleware-linux/files/8134216/output-build-README.txt)

.

**Comment by M0Rf30** [comment]
> Ciao a tutti, @ruphy mi ha allertato sullo stato di questo repository, ho letto questo thread e mi dispiace molto non essere arrivato prima e sopratutto che da ben due anni la situazione sia andata ristagnandosi sempre di più.
> 
> @M0Rf30 e tutti per scambiare due parole e sopratutto in libertà raggiungetemi sul canale slack di developers italia, è un luogo agevole per noi developers.
> 
> Se fossimo d'accordo @M0Rf30 io ti proporrei di aprire una PR, così faccio una rapidissima revisione e la unisco subito, dopodiché ci organizziamo su come mantenere questo repository e con dei ruoli chiari e agevoli per tutti
> 
> poi, a latere, faremo due chiacchiere per eludere il problema di aggiornamento/collisione di libcrypto++ che mi sembra tanto semplice quanto devastante :-)
> 
> Io ci sono, partiamo subito, datemi cenno

Ue @peppelinux che fine hai fatto? quanto mi piace avere ragione. "partiamo subito", si a prendere per il culo le persone
