### ISSUE TITLE
Impossibile aggiungere il modulo su Ubuntu 22.04.2

### ISSUE THREAD

**Issue by MircoTorelli** [italia/cie-middleware-linux#61]
Ubuntu 22.04.2
firefox 114.0.2
cie-middleware  1.4.3-4
Quando provo a caricare la libreria /usr/local/lib/libcie-pkcs11.so in firefox ricevo il messaggio di  errore "Impossibile aggiungere il modulo", la app java funziona correttamente e mi legge la CIE

**Comment by aantetomaso** [comment]
Ciao Mirco,

puoi verificare se il modulo è presente nel path indicato e se il path è specificato correttamente? In caso puoi rimuovere il Software CIE con il comando sudo dpkg --purge cie-middleware e reinstallare l'ultima versione disponibile, la 1.4.3.6?
Grazie.
