### ISSUE TITLE
Login automatico dopo il pairing

### ISSUE THREAD

**Issue by DeadLockStarve** [italia/cie-middleware-linux#67]
Non sarebbe meglio permettere il signing di un certificato proprio con la CIE e successivamente eseguire con esso il login sui siti? Eviterebbe l'inconveniente di dover tenere la CIE sempre a portata di mano

**Comment by aantetomaso** [comment]
L'accesso con la CIE ai siti della PA avviene per il tramite di Entra con CIE, il cui meccanismo di funzionamento è stato notificato alla Commissione Europea ai sensi del Regolamento eIDAS. In ogni caso, lo schema Entra con CIE è stato potenziato con credenziali di livello basso e significativo che non richiedono l'uso della CIE. Per maggiori informazioni, www.cartaidentita.it.
