### ISSUE TITLE
Firma grafica non funzionante

### ISSUE THREAD

**Issue by FVA-Bit4ID** [italia/cie-middleware-linux#73]
Problemi riguardante la firma grafica custom attraverso il caricamento di un PNG.
Quando viene generata la firma con il middleware CIE-ID esce un blocco nero, facile da verificare aprendo il il PDF firmato con Adobe.

**Comment by rogueai** [comment]
Il problema sembra essere sulla lib ghost4j, da quello che vedo non e' piu' mantenuta. 

Tra i vari fork di cie-middleware-linux, uno in particolare usa apache pdfbox al suo posto con cambiamenti minimi al codice.

**Comment by AntonioCiccarelli** [comment]
Risolto nella 1.4.3.9
